alias h="homeshick"
alias l="ls -la"

alias edit-bash-conf="$EDITOR $HOME/.bashrc"
alias edit-bash-local="$EDITOR $HOME/.bashrc.local"
alias edit-zsh-conf="$EDITOR $HOME/.zshrc"
alias edit-zsh-local="$EDITOR $HOME/.zshrc.local"
alias reload-bash="source $HOME/.bashrc"
alias reload-zsh="source $HOME/.zshrc"
alias ssh-office="ssh office.local"
